config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'welcome/documentation'

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :appointments
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :appointment_imports
    end
  end

  resources :appointment_imports do
    collection { post :import }
  end

  resources :appointments do
   collection do
     post 'search', to: 'appointments#search'
   end
  end

  resources :appointment_imports do
    collection do
      post 'search', to: 'appointment_imports#search'
    end
  end

  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  require 'csv'
  validates :first_name, :last_name, :start_date,    presence: true
  validates :start_time,    presence: true,
            uniqueness: { scope: :start_date }

  validate :start_date_cannot_be_in_the_past


  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if
        end_date.blank? and Date.strptime(self.start_date, '%m/%d/%Y') < Date.today
  end


end

app/models/appointment_import.rb
class AppointmentImport < ActiveRecord::Base

  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      AppointmentImport.create! row.to_hash
    end
  end

  def duration
    if self.end_time.present?
      ((self.end_time.gsub(':', '.').to_f - self.start_time.gsub(':', '.').to_f) *100).round(0)
    end
  end
end

app/controllers/api/v1/appointment_imports_controller.rb
module Api
  module V1
    class AppointmentImportsController < ApplicationController
      respond_to :json

      def index
        respond_with AppointmentImport.all
      end

      def show
        respond_with AppointmentImport.find(params[:id])
      end

      def create
        respond_with AppointmentImport.create(params[:appointment_import])
      end

      def update
        respond_with AppointmentImport.update(params[:id], params[:appointment_import])
      end

      def destroy
        respond_with AppointmentImport.destroy(params[:id])
      end
    end
  end
end

app/controllers/api/v1/appointments_controller.rb
module Api
  module V1
    class AppointmentsController < ApplicationController
      respond_to :json

      def index
        respond_with Appointment.all
      end

      def show
        respond_with Appointment.find(params[:id])
      end

      def create
        respond_with Appointment.create(params[:appointment])
      end

      def update
        respond_with Appointment.update(params[:id], params[:appointment])
      end

      def destroy
        respond_with Appointment.destroy(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointment_imports_controller.rb
class AppointmentImportsController < ApplicationController
  before_action :set_appointment_import, only: [:show, :edit, :update, :destroy]

  def search
    @appointment_imports = AppointmentImport.where('start_time like ?', "%#{params[:search_query]}%")
    render template: 'appointment_imports/index'

  end
  def index
    @appointment_imports = AppointmentImport.all
  end


  def show
  end

  def new
    @appointment_import = AppointmentImport.new
  end

  def edit
  end


  def create
    @appointment_import = AppointmentImport.new(appointment_import_params)

    respond_to do |format|
      if @appointment_import.save
        format.html { redirect_to @appointment_import, notice: 'Appointment import was successfully created.' }
        format.json { render :show, status: :created, location: @appointment_import }
      else
        format.html { render :new }
        format.json { render json: @appointment_import.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    AppointmentImport.import(params[:file])
    redirect_to root_url, notice: 'Appointments imported.'
  end


  def update
    respond_to do |format|
      if @appointment_import.update(appointment_import_params)
        format.html { redirect_to @appointment_import, notice: 'Appointment import was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment_import }
      else
        format.html { render :edit }
        format.json { render json: @appointment_import.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment_import.destroy
    respond_to do |format|
      format.html { redirect_to appointment_imports_url, notice: 'Appointment import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_appointment_import
      @appointment_import = AppointmentImport.find(params[:id])
    end

    def appointment_import_params
      params.require(:appointment_import).permit(:start_date, :start_time, :end_date, :end_time, :first_name, :last_name, :comments)
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  require'csv'


  def search
    @appointments = Appointment.where('start_time like ?', "%#{params[:search_query]}%")
    render template: 'appointments/index'
  end

  def index
    @appointments = Appointment.all
  end


  def show
  end

  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:start_date, :start_time, :end_date, :end_time, :first_name, :last_name, :comments)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def documentation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_imports_helper.rb
module AppointmentImportsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appointment_imports/_form.html.erb
<%= form_for(@appointment_import) do |f| %>
  <% if @appointment_import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment_import.errors.count, "error") %> prohibited this appointment_import from being saved:</h2>

      <ul>
      <% @appointment_import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointment_imports/edit.html.erb
<h1>Editing appointment_import</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment_import %> |
<%= link_to 'Back', appointment_imports_path %>

app/views/appointment_imports/index.html.erb
<%= form_tag search_appointment_imports_path, class: 'form' do %>
<%= text_field_tag "search_query", nil, placeholder: 'enter start time' %>
<%= submit_tag "Search", class: 'radius button tiny'%>
<% end %>
<br>
<br>

<%= form_tag import_appointment_imports_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import' %>
<% end %>



<h1>Listing appointment_imports</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Start time</th>
      <th>End date</th>
      <th>End time</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment_imports.each do |appointment_import| %>
      <tr>
        <td><%= appointment_import.start_date %></td>
        <td><%= appointment_import.start_time %></td>
        <td><%= appointment_import.end_date %></td>
        <td><%= appointment_import.end_time %></td>
        <td><%= appointment_import.first_name %></td>
        <td><%= appointment_import.last_name %></td>
        <td><%= appointment_import.comments %></td>
        <td><%= link_to 'Show', appointment_import %></td>
        <td><%= link_to 'Edit', edit_appointment_import_path(appointment_import) %></td>
        <td><%= link_to 'Destroy', appointment_import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Home', root_path %>

app/views/appointment_imports/new.html.erb
<h1>New appointment_import</h1>

<%= render 'form' %>

<%= link_to 'Back', appointment_imports_path %>

app/views/appointment_imports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @appointment_import.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment_import.start_time %>
</p>

<p>
  <strong>End date:</strong>
  <%= @appointment_import.end_date %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment_import.end_time %>
</p>

<p>
  <strong>First name:</strong>
  <%= @appointment_import.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @appointment_import.last_name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @appointment_import.comments %>
</p>

<%= link_to 'Edit', edit_appointment_import_path(@appointment_import) %> |
<%= link_to 'Back', appointment_imports_path %>

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date,class: 'start_date' %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time,class: 'start_time' %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<%= form_tag search_appointments_path, classa: 'form' do %>
    <%= text_field_tag "search_query", nil, placeholder: 'Search text' %>
    <%= submit_tag "Search", class: 'radius button tiny' %>
<% end %>


<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Start time</th>
      <th>End date</th>
      <th>End time</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.start_date %></td>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.end_date %></td>
        <td><%= appointment.end_time %></td>
        <td><%= appointment.first_name %></td>
        <td><%= appointment.last_name %></td>
        <td><%= appointment.comments %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @appointment.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End date:</strong>
  <%= @appointment.end_date %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<p>
  <strong>First name:</strong>
  <%= @appointment.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @appointment.last_name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @appointment.comments %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApptSetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/documentation.html.erb
<h1 align="center">App Setter API v1 </h1>

<h4 align="center">The App Setter api allows you to create a new appointment or upload past appointments into the database.
   The query's default setting returns json.</h4>

<ol align="center">There are two main API calls.</ol>
	<li align="center">The first returns future appointments(must create new appointment first):
	(API CALL)</li>

    <li align="center"> The second returns previous appointments(must upload csv file)
	(2nd ap call)</li>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p><%= link_to 'Create a New Appointment', new_appointment_path %>
</p>


<p><%= link_to 'Upload Appointments', appointment_imports_path %>
</p>

<p><a href="https://app-setter.herokuapp.com/api/v1/appointment_imports">View uploaded appointments api</a></p>
<p><a href="https://app-setter.herokuapp.com/api/v1/appointments">View new appointments api</a></p>(must create a new appointment first)